services:
  # 트레이딩 봇 서비스
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    restart: unless-stopped
    env_file:
      - .env  # 호스트의 .env 파일을 컨테이너 환경 변수로 사용
    volumes:
      # 데이터베이스 파일 영속성을 위해 볼륨 마운트
      - /home/ubuntu/docker/aitrade/bitcoin_trading.db:/app/bitcoin_trading.db
      # 로그 파일 영속성을 위해 볼륨 마운트 (선택 사항)
      - /home/ubuntu/docker/aitrade/bitcoin_trading.log:/app/bitcoin_trading.log
    command: ["python", "main.py"]
    networks:
      - trading_network

  # Streamlit 대시보드 서비스
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: unless-stopped
    ports:
      # 호스트의 8501 포트를 컨테이너의 8501 포트로 연결
      - "8501:8501"
    volumes:
      # 봇과 동일한 데이터베이스 파일을 읽기 전용으로 마운트
      - /home/ubuntu/docker/aitrade/bitcoin_trading.db:/app/bitcoin_trading.db:ro
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - trading_bot  # 봇이 먼저 시작되도록 의존성 설정 (선택 사항)
    networks:
      - trading_network

networks:
  trading_network: 